Add "get_all_pages" function to all endpoints
mlemesle/rustemon pull request #15
Opened 2023-01-07 22:45 UTC by ChaseParate

This is a more convenient way to get all of the resources from a given endpoint.

2023-01-13 13:35 UTC, mlemesle commented
Hey @ChaseParate !

Do you plan to do the changes or should I take care of it ? I'd like to make a release soon :slightly_smiling_face: 

Please let me know, thanks

2023-01-13 13:37 UTC, mlemesle requested changes

2023-01-13 13:37 UTC, mlemesle commented on src/endpoint.rs
> +        pub async fn get_all_pages(rustemon_client: &RustemonClient) -> Result<Vec<NamedApiResource<$type>>, Error> {
This can be reworked in order to use the `next` field in `NamedApiResourceList`

2023-01-14 03:15 UTC, ChaseParate commented
Sorry, I've been super busy! I've just implemented the changes you mentioned and it seems much more concise! I was wondering if the function should be named "get_all" or "get_all_resources" instead of "get_all_pages". What do you think?

2023-01-14 03:27 UTC, ChaseParate commented
Also, perhaps there is a way to return the paginated data without needing to await every page? Something like a [Stream](https://docs.rs/futures/latest/futures/stream/trait.Stream.html) comes to mind, but I'm not too familiar with the `futures` crate.

2023-01-14 03:30 UTC, ChaseParate reviewed
This was a mistake: I just synced up my fork to the main repo.

2023-01-14 10:11 UTC, mlemesle commented
Hey there, no worries !

Thanks for the update, this is much more readable.

Regarding `futures` to avoid awaiting every pages, do you wanna do it ? Please let me know :slightly_smiling_face:

2023-01-14 18:10 UTC, ChaseParate commented
I did a few prototypes with `Stream`s, but I just couldn't quite get it to work. Maybe it would be worthwhile to investigate later.

2023-01-18 16:10 UTC, mlemesle approved these changes

2023-01-18 16:10 UTC, mlemesle commented
Thanks for your contribution !

2023-01-18 16:10 UTC, merged