Improve `get_all_pages`
mlemesle/rustemon pull request #17
Opened 2023-05-16 22:41 UTC by ChaseParate

Right now, the `get_all_pages` endpoint function is very slow. It uses the `get_page` function, which defaults to retrieving only 20 entries in a row. Thus, when trying to fetch all entries from a resource with many entries (such as `rustemon::pokemon::pokemon_species`, which contains over a thousand entries), many extraneous requests are sent, which greatly impacts performance. This can be fixed by lowering the number of requests and asking for the proper amount of entries within the requests. 

I also updated one of the examples, which displays the increased performance.

2023-05-22 14:35 UTC, mlemesle requested changes

2023-05-22 14:35 UTC, mlemesle commented on src/endpoint.rs
> +            let mut other_entries = get_page_with_param(first_page_entries_count, other_entries_count, &rustemon_client).await?;
Can you please remove the `&` before rustemon_client please ? 
I believe it's not necessary

2023-05-22 17:17 UTC, ChaseParate commented
Got it!

2023-05-27 15:22 UTC, mlemesle approved these changes

2023-05-27 15:22 UTC, merged